// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StajDb;

#nullable disable

namespace StajDb.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StajDb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Telefon",
                            Slug = "telefon",
                            UpdatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDeleted = false,
                            Name = "Elektronik",
                            Slug = "elektronik",
                            UpdatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        });
                });

            modelBuilder.Entity("StajDb.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Features", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            DataType = "string",
                            IsDeleted = false,
                            Name = "Renk",
                            UpdatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            DataType = "string",
                            IsDeleted = false,
                            Name = "Depolama",
                            UpdatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        });
                });

            modelBuilder.Entity("StajDb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Örnek ürün.",
                            ImageUrl = "watch-8.jpeg",
                            IsDeleted = false,
                            Name = "Apple Watch 8",
                            Status = "active",
                            Stock = 25,
                            UpdatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Description = "Örnek ürün.",
                            ImageUrl = "watch-9.jpeg",
                            IsDeleted = false,
                            Name = "Apple Watch 9",
                            Status = "active",
                            Stock = 10,
                            UpdatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        });
                });

            modelBuilder.Entity("StajDb.Models.ProductFeatureValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("ProductId", "FeatureId")
                        .IsUnique();

                    b.ToTable("ProductFeatures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            FeatureId = 1,
                            ProductId = 1,
                            UpdatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            Value = "Siyah"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            FeatureId = 2,
                            ProductId = 1,
                            UpdatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            Value = "41mm"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            FeatureId = 1,
                            ProductId = 2,
                            UpdatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            Value = "Gümüş"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            FeatureId = 2,
                            ProductId = 2,
                            UpdatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed",
                            Value = "45mm"
                        });
                });

            modelBuilder.Entity("StajDb.Models.ProductPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDiscount")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("[EndDate] IS NULL");

                    b.ToTable("ProductPrices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDiscount = false,
                            Price = 20000m,
                            ProductId = 1,
                            StartDate = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            IsDiscount = false,
                            Price = 30000m,
                            ProductId = 2,
                            StartDate = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = "seed"
                        });
                });

            modelBuilder.Entity("StajDb.Models.Product", b =>
                {
                    b.HasOne("StajDb.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StajDb.Models.ProductFeatureValue", b =>
                {
                    b.HasOne("StajDb.Models.Feature", "Feature")
                        .WithMany("Values")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StajDb.Models.Product", "Product")
                        .WithMany("FeatureValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StajDb.Models.ProductPrice", b =>
                {
                    b.HasOne("StajDb.Models.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StajDb.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StajDb.Models.Feature", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("StajDb.Models.Product", b =>
                {
                    b.Navigation("FeatureValues");

                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
